### PR TITLE
115 fix width share image

### LINKED ISSUE #115: sharing a post modal content is too wide in Firefox and IE
the contents of the modal do not have restricted width:
Firefox:
screen shot 2015-03-09 at 09 59 51
IE:
screen shot 2015-03-09 at 12 28 09

### PR DESCRIPTION
**Pull request by adrianwhite**
@fulv I think this should be straightforward to merge as is a very simple change.

Waffle.io:
closes #115

### CODE REVIEW

**Comment by adrianwhite** [comment]
waffle:
connect to #155

**Comment by adrianwhite** [comment]
This work connects to #115

**Comment by adrianwhite** [comment]
closes #115

**Comment by adrianwhite** [comment]
Waffle.io:
closes #115

**Comment by fulv** [comment]
Hmm... why did the build fail?

**Comment by fulv** [comment]
This is why I love CI.  A WHITESPACE change allegedly breaks the build.  Classic.

**Comment by adrianwhite** [comment]
Odd. I'll take a look.

**Comment by adrianwhite** [comment]
Ah, that's better.

**Pull request merged**
