### PR TITLE
heme plugin and views to be able to enable and disable theme per user session.

### PR DESCRIPTION
**Pull request by lewicki**
There are new views '@@enable_theme' and '@@disable_theme' that allow user to disable theming in current session.

### CODE REVIEW

**Comment by reinhardt** [comment]
Sorry, this had been closed by mistake.

**Comment by maartenkling** [comment]
please merge in master

**Comment by maartenkling** [comment]
@lewicki can you please rebase or merge in master, this is a taks for the ploneintranet stack, all branches should be uptodate tnx

**Comment by fulv** [comment]
Minor nitpick:  _barceloneta_ is spelled with one **t**

**Comment by fulv** [comment]
Also, how about using a cookie, as @davisagli suggested?

**Comment by fulv** [comment]
From our recollection this was made when ploneintranet was still on Plone 4, so we should check that it works after all our refactoring.

**Comment by wengole** [comment]
Have create #135 to replace this as the change will require reimplementing

**Pull request closed without merging**
