### PR TITLE
Add pat-checklist-picker to build

### PR DESCRIPTION
**Pull request by tax**
Add [pat-checklist-picker](https://github.com/ploneintranet/pat-checklist-picker) to theme. This enables the picker to preserve state and keep everything on the clientside.

### CODE REVIEW

**Comment by tax** [comment]
@gyst Who can I contact to review this PR

**Comment by do3cc** [comment]
This PR cannot be merged in its current state, as it has failing tests:
http://jenkins.ploneintranet.net/job/Plone%20Intranet%20Theme/425/console

**Comment by fulv** [comment]
I'll review it after the failing tests are fixed.

**Comment by fulv** [comment]
Connect #102

**Comment by fulv** [comment]
I will look at the bower loading issue.

**Comment by fulv** [comment]
@cornae, @tax we will review together

**Pull request merged**
