### PR TITLE
inline tags and mentions tooltips

### PR DESCRIPTION
**Pull request by adrianwhite**
To be able to have unique ids for injecting tags and mentions we have ad to 'inline' the tags and mentions tooltips for each update/comment form.
I think @gyst needs it in the live demo site by Thursday 5th Feb.
@cornae, you are probably best suited to review and merge this.

### CODE REVIEW

**Comment by adrianwhite** [comment]
This should resolve #38

**Comment by adrianwhite** [comment]
Whilst investigating #72 I realise I have actually made a mistake here and am not targeting my markup to be included into the tooltips correctly.
I'll fix that and re-issue the pull request as I think this one may introduce other issues if merge too early.

**Comment by adrianwhite** [comment]
I've fixed an issue where search results for users to mention were appearing in the side bar.
There is still an issue where you cannot see in the tooltip any results of searching for users or tags. This is WIP on issue #72.

**Comment by gyst** [comment]
Discussed and closing without merge: this would pollute the markup and confuse developers.

**Pull request closed without merging**
