### PR TITLE
Duplicate ids

### PR DESCRIPTION
**Pull request by adrianwhite**
@fulv, I'm not sure who is best to review this. Please could you assign as you feel appropriate.

This should hopefully go some way to resolving the issue #16 and #72.

#16 will only be 'resolved' for the first instances of the search results, tag and mention tootips due to restrictions of the static nature of the prototype site.

#72 is resolved by adding missing ```searchresult``` parameters to includes of panel-tags and panel-mentions.

I'm sorry this pull request is made slightly more complicated by fixing two issues in one but I had to sort out #72 to complete the fix for #16.

Notes for waffle.io:

Connect to #72 
Connect to #16

### CODE REVIEW

**Comment by fulv** [comment]
I'm reviewing.

**Comment by fulv** [comment]
Reviewed, looks good.  Can you please resolve the merge conflicts that have cropped up in the meantime?  Then we can merge.

**Comment by adrianwhite** [comment]
@fulv rebased master onto this branch.
Should be good to go now.

**Comment by adrianwhite** [comment]
I think I may have done somehting funny with GIT here and the rebase is showing as new commits. I'll try to sort it out.

**Comment by adrianwhite** [comment]
Notes for waffle.io:

Connect to #72 
Connect to #16

**Comment by fulv** [comment]
Ack!  It's a moving target!  I'm awake now...

**Comment by adrianwhite** [comment]
I'm going to have to rebase again.

**Comment by adrianwhite** [comment]
Hmmm I think this pull request may have got a little out of hand. I may create a new branch off master and cherry pick my two commits into it so that it will be clearer what has changed here.

**Comment by fulv** [comment]
Thanks :-)

**Comment by adrianwhite** [comment]
Simplified in #95

**Pull request closed without merging**
